export const Actions = {
  GET_POSITIONS: "GET_POSITIONS",
  GET_ARTISTS_REQUEST: "GET_ARTISTS_REQUEST",
  GET_ARTISTS_SUCCESS: "GET_ARTISTS_SUCCESS",
  FILTER_ARTISTS: "FILTER_ARTISTS",
  GET_PLAYERS_ERROR: "GET_PLAYERS_ERROR"
};
