export const Actions = {
  GET_POSITIONS: "GET_POSITIONS",
  GET_ARTISTS_REQUEST: "GET_ARTISTS_REQUEST",
  GET_ARTISTS_SUCCESS: "GET_ARTISTS_SUCCESS",
  LOAD_MORE_REQUEST: "LOAD_MORE_REQUEST",
  LOAD_MORE_SUCCESS: "LOAD_MORE_SUCCESS",
  FILTER_ARTISTS: "FILTER_ARTISTS",
  GET_PLAYERS_ERROR: "GET_PLAYERS_ERROR",
  SELECTED_ARTIST: "SELECTED_ARTIST"
};
